### ISSUE TITLE
Dependency().Resolve(() => _mediator' fails in NotificationRule.cs

### ISSUE THREAD

**Issue by sleeklogic** [AquaNerd/NRulesAdapter#2]
Hi @AquaNerd I've been looking at DI for NRules using your NRulesAdapter example... but out of the box clone of the repo running in VS2019 is failing to successfully resolve the mediator dependency in NotificationRule.cs, which ends up with a null reference exception when the PingCommand attempt occurs. I'm assuming that you have/had the solution running without error and I'm at a loss as to why the dependency resolve is failing... I've trialed some mods to the code per the NRules Unit test rule dependency examples but nothing seems to be working. Any assistance with this greatly appreciated.

**Comment by AquaNerd** [comment]
@sleeklogic Sorry I have been on vacation so I have not had the time to look at answering your questions. Let me take some time to pull this code back down and see if I have an answer for you. It may take me a bit since I balance this with my day job.

**Comment by sleeklogic** [comment]
@AquaNerd Thanks

**Comment by sleeklogic** [comment]
Hi @AquaNerd I've had another look at the code in NotificationRule.cs and if a change is made to pass _mediator to the SetNotifiedUser function, then the dependency resolution then the error is resolved.. so only a small change to your code. I'll close the Issue accordingly
